Improve validation splitter

diff --git a/experiments/slurm/run-master b/experiments/slurm/run-master
--- a/experiments/slurm/run-master
+++ b/experiments/slurm/run-master
@@ -2,21 +2,23 @@
 set -e
 # run from "experiments" dir
 cd "${0%/*}/.."
-DATASETS=(Coffee CBF ECG200 TwoPatterns Wafer)
-# ALGS=(all all ects ecdire relclass srcf earliest)
-# METHODS=(mo so mo mo mo mo mo)
-ALGS=(all all earliest)
-METHODS=(mo so mo)
+DATASETS=(Coffee CBF ECG200 TwoPatterns Wafer Fish GestureMidAirD3 OliveOil Phoneme)
+ALGS=(all all fixed ects edsc ecdire srcf relclass teaser ecec earliest)
+METHODS=(mo so mo mo mo mo mo mo mo mo mo)
 CONFJOBS=()
 TESTJOBS=()
-REPS=2
+REPS=25
 export UCR_ROOT="/scratch/ottervanger/UCR/"
-export PARTITION="graceTST"
-export EXCLUDE="ethnode[01-10,23]"
+export PARTITION="graceADA"
+export EXCLUDE="ethnode[23]"
 export GLOBAL_SEED=0
 START=$GLOBAL_SEED
 
 for DATASET in ${DATASETS[*]}; do
+    if ! python util/validationsplitter.py --folds=5  --seed=$GLOBAL_SEED --reps=$REPS "${UCR_ROOT}${DATASET}/${DATASET}_TRAIN.tsv" &> /dev/null; then
+        printf "%20s: \e[31mFailed to split dataset.\e[0m\n" $DATASET
+        continue
+    fi
     for i in ${!METHODS[*]}; do
         METHOD=${METHODS[i]}
         ALG=${ALGS[i]}
@@ -39,6 +41,7 @@ for DATASET in ${DATASETS[*]}; do
         [ -z "$CONFJOB" ] || scontrol release ${CONFJOB}
         TESTJOBS+=($TESTJOB)
     done
+    printf "%20s: Jobs submitted.\n" $DATASET
 done
 printf "Submitted batch %3d jobs for configuration\n" "${#CONFJOBS[@]}"
 printf "Submitted batch %3d jobs for test evaluation\n" "${#TESTJOBS[@]}"
